version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    container_name: mysql
    image: cekharch/mysql:v1
    volumes:
      - mysql:/var/lib/mysql
  backend:
    container_name: backend
    image: cekharch/backend:v1
    command: sh -c "sleep 100 && node /opt/serer/index.js"
    depends_on:
      - mysql
  frontend:
    container_name: frontend
    image: cekharch/frontend:v1
    ports:
      - 80:80
    depends_on:
      - backend